// Agent 5: Freshdesk Note Writer
//
// Model: claude-haiku-4-5-20251001
//
// Takes the retention brief + gap audit and formats them into a clean
// internal Freshdesk note, then posts it to the ticket.
//
// Architecture: hybrid rendering
//   - Haiku generates the narrative sections (agentBrief, S1, S2) — benefits from
//     natural language interpretation of scripts and commitments
//   - TypeScript builds Section 3 and the footer — structured data (escalation
//     sequence array) must be rendered deterministically, not inferred from JSON
//
// This avoids the common failure mode of asking a model to expand a structured
// array from a vague bracket instruction — the escalation sequence is 5 typed
// objects and must always render completely and in order.

import type { RetentionBrief, GapAuditResult, FinancialOption } from './types';
import { getAnthropicApiKey } from '@/lib/secrets';
import { getFreshdeskCredentials } from '@/lib/secrets';

// ── TSI product name map — never expose vendor names to agents ───────────────
// Mirrors the service key table in context.ts using client-facing TSI names only.
const SERVICE_KEY_LABELS: Record<string, string> = {
  W: 'Website',
  O: 'SEO',
  Y: 'Directories',
  T: 'Targeting Ads',
  S: 'Social',
  E: 'E-Commerce',
  F: 'Facebook Ads',
  V: 'BMP',
  Z: 'Lead Nurturing',
  C: 'Call Trace',
  P: 'Call Trace Pro',
};

function renderProducts(serviceKeys: string[]): string {
  // serviceKeys from Falcon are bundled strings e.g. ["WOYTZ"] — split first
  const expanded = serviceKeys.flatMap((k) => k.split(''));
  const labels = expanded.map((k) => SERVICE_KEY_LABELS[k] ?? k);
  return labels.join(' · ');
}

// ── At-risk header value ──────────────────────────────────────────────────────
// Shows pipeline value when non-zero (V clients with active BMP pipeline/invoices).
// Falls back to annualized contract value when pipeline is zero (BMP Lite clients,
// or BMP clients with an empty pipeline) so the header always shows something useful.
function computeAtRiskHeader(
  pipelineAtRisk: number,
  monthlyPrice: number | null
): { label: string; value: string } {
  if (pipelineAtRisk > 0) {
    return { label: 'Pipeline at risk', value: `$${pipelineAtRisk.toLocaleString()}` };
  }
  if (monthlyPrice && monthlyPrice > 0) {
    return { label: 'Annual value', value: `~$${(monthlyPrice * 12).toLocaleString()}/yr` };
  }
  return { label: 'At risk', value: 'N/A' };
}

// ── TypeScript-rendered Section 3 ────────────────────────────────────────────
// Never delegated to the model. Structured data → deterministic HTML.

function renderFinancialOption(opt: FinancialOption, stepNumber: number): string {
  const mgr = opt.requiresManager ? ' <b>⚠️ MGR</b>' : '';
  // Trim script to first sentence — max ~15 words in practice
  const script = opt.script.split(/(?<=[.?!])\s+/)[0] ?? opt.script;
  return `<li>${stepNumber}. ${opt.label}${mgr} — &ldquo;${script}&rdquo;</li>`;
}

function buildSection3Block(
  brief: RetentionBrief,
  gapAudit: GapAuditResult | null,
  topGaps: string[]
): string {
  const s3 = brief.section3;
  const sequence = s3.escalationSequence ?? [];

  const sequenceHtml = sequence.length > 0
    ? `<ol>${sequence.map((opt, i) => renderFinancialOption(opt, i + 1)).join('\n')}</ol>`
    : '<i>No escalation options.</i>';

  const gapFooter = topGaps.length > 0
    ? `<b>🔍 Top gaps:</b><ul>${topGaps.map(g => `<li>${g}</li>`).join('')}</ul><hr>`
    : '';

  return `<hr>
<b>Section 3 — Economics &nbsp;⚠️ LAST RESORT — only after S1 + S2 rejected</b><br>
${sequenceHtml}
<hr>
${gapFooter}
<p><i>Generated by TSI Retention Agent &middot; ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</i></p>`;
}

// ── Haiku prompt: narrative sections only (agentBrief, S1, S2) ───────────────
// TARGET: SHORT. An agent glances at this before dialing. Every field should be
// readable in 5 seconds. No paragraph narration — bullets only. Scripts max 2 sentences.

function buildNotePrompt(
  brief: RetentionBrief,
  gapAudit: GapAuditResult | null,
  clientName: string,
  agentNotes: string,
  productsLine: string,
  atRisk: { label: string; value: string }
): string {
  const tsiServiceGapNote = gapAudit?.tsiServiceGap
    ? `⚠️ TSI SERVICE GAP — ${gapAudit.topGap}`
    : '';

  const isUnderContract = brief.agentBrief?.contractNote?.includes('UNDER CONTRACT') ?? false;

  return `You are writing a SCANNABLE internal Freshdesk note for a CSR who will dial this client in the next 60 seconds. Write clean HTML using ONLY: <b>, <br>, <ul>, <li>, <hr>. No paragraphs. No narration. Bullets only.

TWO REGISTERS — CRITICAL:
The "Before you dial" section (Snapshot, Cancel read, Lead with, Context, TSI, Notable bullets) is INTERNAL — the agent reads it privately. You MAY include honest TSI context here, including service gaps, LCR issues, and data limitations.
The Section 1 and Section 2 scripts are SPOKEN TO THE CLIENT. NEVER include TSI failure language, apologies, or "we haven't done X" in scripts. Scripts must be forward-looking, confident, and specific.

PRODUCT NAMING — CRITICAL: Never use vendor names. Always use TSI product names: "BMP" or "Growth Management" (not vcita), "Directories" (not Yext), "Website" (not Duda). GBP / Google Business Profile is fine.

BREVITY RULES:
- clientSnapshot: 1 bullet, max 20 words. Tenure + vertical + what's at stake.
- cancelReasonRead: 1 bullet, max 15 words. The real reason, plainly stated.
- leadWith: 1 bullet, max 20 words. Strongest hook — must include a specific number.
- verticalNote: 1 bullet, max 20 words. The one context point the agent needs about this type of business.
- Notable highlights: 1-2 bullets max, 20 words each. Only include if genuinely notable — a strong GBP metric, high review count, significant lead count, or major platform gap. Skip if nothing stands out.
- Section 1 agentScript: 2-3 sentences max. Opening with a specific number → what TSI will do → yes/no closing question.
- Each commitment: "<b>title</b> → plain-English expected impact" — max 15 words per item.
- Section 2 script: 2 sentences. Sentence 1: key loss with a real number. Sentence 2: "Is it okay if all of that happens?"
- Each loss item: "<b>asset name with key number</b> · timing · one-phrase consequence" — Example: <li><b>27 Directories listings</b> · inaccurate within 30 days · customers find wrong hours or number</li>
- emailVersion: DO NOT include in the note — it is in the JSON for reference only
- TOTAL NOTE (S1+S2+brief): target under 250 words of visible text
${isUnderContract ? '\nCONTRACT CLIENT: Put the contract callout FIRST in the Before You Call section. The tone is patient — more time, not panic.' : ''}

Client: ${clientName}
Tenure: ${brief.tenureMonths} months | ${atRisk.label}: ${atRisk.value}
Products: ${productsLine || 'Unknown'}
Agent notes: ${agentNotes || 'None'}
${tsiServiceGapNote ? `INTERNAL CONTEXT (for Before You Dial bullets only — NEVER put in scripts): ${tsiServiceGapNote}` : ''}

Brief data (pull the actual content from here — do not paraphrase):
${JSON.stringify({
  agentBrief: brief.agentBrief,
  section1: { headline: brief.section1.headline, commitments: brief.section1.commitments, agentScript: brief.section1.agentScript },
  section2: { headline: brief.section2.headline, lossTimeline: brief.section2.lossTimeline, yearsOfWorkStatement: brief.section2.yearsOfWorkStatement, agentScript: brief.section2.agentScript },
  pipelineAtRisk: brief.pipelineAtRisk,
  tenureMonths: brief.tenureMonths,
}, null, 2)}

Write this EXACT HTML structure — fill every bracketed item with real content from the brief data above:

<b>🔴 ${clientName.toUpperCase()} — RETENTION BRIEF</b><br>
<b>Tenure:</b> ${brief.tenureMonths}mo &nbsp;|&nbsp; <b>${atRisk.label}:</b> ${atRisk.value}<br>
<b>Products:</b> ${productsLine}<br>
<hr>
${brief.agentBrief?.contractNote ? `<b>${brief.agentBrief.contractNote}</b><br>` : ''}<b>📋 Before you dial:</b>
<ul>
<li><b>Snapshot:</b> [1-bullet clientSnapshot — max 15 words]</li>
<li><b>Cancel read:</b> [1-bullet cancelReasonRead — max 12 words]</li>
<li><b>Lead with:</b> [1-bullet leadWith — the hook, max 15 words]</li>
<li><b>Context:</b> [1-bullet verticalNote — max 15 words]</li>
${brief.agentBrief?.tsiServiceNote || gapAudit?.tsiServiceGap ? `<li><b>⚠️ TSI:</b> [brief.agentBrief.tsiServiceNote or gapAudit topGap — 1 line max, internal context only, never in scripts]</li>` : ''}
[If anything is genuinely notable from the data — strong GBP metrics, high review count, significant lead volume, or a major gap — add 1-2 <li><b>Notable:</b> [finding — max 20 words]</li> bullets here. Skip entirely if nothing stands out.]
</ul><hr>
<b>Section 1 — Opportunity</b><br>
<b>Open with:</b> [brief.section1.headline]<br>
<b>Commitments:</b>
<ul>
[one <li> per commitment: <b>title</b> — expected impact, max 10 words each]
</ul>
<b>Script (2 sentences ONLY):</b> [Opening sentence from brief.section1.agentScript — the hook with 1 number. Then a direct yes/no question. CONDENSE — do not copy the full script.]<br><hr>
<b>Section 2 — Fear / Loss</b><br>
<b>Open with:</b> [brief.section2.headline]<br>
<b>What goes away:</b>
<ul>
[one <li> per loss item — FORMAT STRICTLY: <b>asset name + key number</b> · timing. NO full sentences. Example: <b>$100k pipeline + 21 invoices</b> · gone Day 1]
</ul>
<b>[brief.section2.yearsOfWorkStatement — CONDENSE to 1 short sentence, max 15 words]</b><br>
<b>Script (2 sentences ONLY):</b> [Sentence 1 from brief.section2.agentScript — the biggest loss in 1 sentence. Then: "Is it okay if all of that happens?"]<br>

RULES:
- BULLETS ONLY — no paragraph prose anywhere in the output
- Fill ALL bracketed placeholders with actual content from the brief data
- Return ONLY the HTML — no markdown, no preamble, no explanation
- Do NOT close with <hr> — the system appends Section 3 after your output
- If a field would make you write a paragraph, cut it to a bullet`;
}

// ── Main export ───────────────────────────────────────────────────────────────

export async function writeRetentionNote(
  ticketId: number,
  brief: RetentionBrief,
  gapAudit: GapAuditResult | null,
  clientName: string,
  agentNotes: string,
  serviceKeys: string[] = [],
  monthlyPrice: number | null = null,
): Promise<{ noteId: number; noteUrl: string }> {

  // Pre-compute TypeScript-rendered header values
  const productsLine = renderProducts(serviceKeys);
  const atRisk = computeAtRiskHeader(brief.pipelineAtRisk, monthlyPrice);

  // Pre-compute top gaps for the footer (TypeScript, not model)
  // Filter out any gap summaries that contain mea culpa language about provisioning —
  // these come from fetch failures misread as setup failures by the gap auditor model.
  // The agent should never see "never activated" or "broken connection" in the gap footer.
  const MEA_CULPA_GAP_PATTERNS = [
    /never activated/i,
    /never been activated/i,
    /broken connection/i,
    /never set up/i,
    /never provisioned/i,
    /not provisioned/i,
    /has a broken/i,
    /appears to have never/i,
    /never configured/i,
  ];
  const topGaps = (gapAudit?.prioritizedGaps?.slice(0, 2) ?? [])
    .filter(g => !MEA_CULPA_GAP_PATTERNS.some(p => p.test(g.summary)))
    .map(g => `${g.dimension.toUpperCase()}: ${g.summary}${g.tsiOwned ? ' [TSI-owned]' : ''}`);

  // Step 1: Haiku generates the narrative sections (agentBrief, S1, S2)
  const apiKey = getAnthropicApiKey();

  const aiResponse = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    signal: AbortSignal.timeout(60_000), // 1-min cap — Haiku is fast; hang = something wrong
    headers: {
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 2000,  // S1+S2+brief only — Section 3 is TypeScript-rendered
      messages: [{
        role: 'user',
        content: buildNotePrompt(brief, gapAudit, clientName, agentNotes, productsLine, atRisk),
      }],
    }),
  });

  if (!aiResponse.ok) {
    const errBody = await aiResponse.text().catch(() => '');
    throw new Error(`Note writer (Haiku) error: ${aiResponse.status} ${aiResponse.statusText}${errBody ? ` — ${errBody.slice(0, 200)}` : ''}`);
  }

  const aiResult = await aiResponse.json() as { content: Array<{ type: string; text: string }> };
  const rawNarrativeHtml = aiResult.content?.[0]?.text;
  if (!rawNarrativeHtml) throw new Error('Empty response from note writer');

  // Strip HTML code fences — Haiku intermittently wraps output in ```html ... ``` despite
  // being told not to. Leading \s* handles newlines Haiku sometimes emits before the fence.
  const narrativeHtml = rawNarrativeHtml
    .replace(/^\s*```(?:html)?\s*/i, '')
    .replace(/\s*```\s*$/i, '')
    .trim();

  // Step 2: TypeScript appends Section 3 (deterministic, no model interpretation)
  const section3Html = buildSection3Block(brief, gapAudit, topGaps);
  const fullNoteHtml = narrativeHtml + '\n' + section3Html;

  // Step 3: Post as internal note to Freshdesk ticket
  const { apiKey: fdApiKey, domain } = await getFreshdeskCredentials();
  const auth = Buffer.from(`${fdApiKey}:X`).toString('base64');

  const fdResponse = await fetch(`https://${domain}/api/v2/tickets/${ticketId}/notes`, {
    method: 'POST',
    headers: {
      'Authorization': `Basic ${auth}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      body: fullNoteHtml,
      private: true,  // internal note — not visible to client
    }),
    signal: AbortSignal.timeout(15000),
  });

  if (!fdResponse.ok) {
    const errText = await fdResponse.text();
    throw new Error(`Freshdesk note POST failed: ${fdResponse.status} — ${errText.slice(0, 200)}`);
  }

  const fdResult = await fdResponse.json() as { id: number };
  return {
    noteId: fdResult.id,
    noteUrl: `https://${domain}/helpdesk/tickets/${ticketId}`,
  };
}
