// Agent 5: Freshdesk Note Writer
//
// Model: claude-haiku-4-5-20251001
//
// Takes the retention brief + gap audit and formats them into a clean
// internal Freshdesk note, then posts it to the ticket.
//
// Architecture: hybrid rendering
//   - Haiku generates the narrative sections (agentBrief, S1, S2) — benefits from
//     natural language interpretation of scripts and commitments
//   - TypeScript builds Section 3 and the footer — structured data (escalation
//     sequence array) must be rendered deterministically, not inferred from JSON
//
// This avoids the common failure mode of asking a model to expand a structured
// array from a vague bracket instruction — the escalation sequence is 5 typed
// objects and must always render completely and in order.

import type { RetentionBrief, GapAuditResult, FinancialOption } from './types';
import { getAnthropicApiKey } from '@/lib/secrets';
import { getFreshdeskCredentials } from '@/lib/secrets';

// ── TSI product name map — never expose vendor names to agents ───────────────
// Mirrors the service key table in context.ts using client-facing TSI names only.
const SERVICE_KEY_LABELS: Record<string, string> = {
  W: 'Website',
  O: 'SEO',
  Y: 'Directories',
  T: 'Targeting Ads',
  S: 'Social',
  E: 'E-Commerce',
  F: 'Facebook Ads',
  V: 'BMP',
  Z: 'Lead Nurturing',
  C: 'Call Trace',
  P: 'Call Trace Pro',
};

function renderProducts(serviceKeys: string[]): string {
  // serviceKeys from Falcon are bundled strings e.g. ["WOYTZ"] — split first
  const expanded = serviceKeys.flatMap((k) => k.split(''));
  const labels = expanded.map((k) => SERVICE_KEY_LABELS[k] ?? k);
  return labels.join(' · ');
}

// ── At-risk header value ──────────────────────────────────────────────────────
// Shows pipeline value when non-zero (V clients with active BMP pipeline/invoices).
// Falls back to annualized contract value when pipeline is zero (BMP Lite clients,
// or BMP clients with an empty pipeline) so the header always shows something useful.
function computeAtRiskHeader(
  pipelineAtRisk: number,
  monthlyPrice: number | null
): { label: string; value: string } {
  if (pipelineAtRisk > 0) {
    return { label: 'Pipeline at risk', value: `$${pipelineAtRisk.toLocaleString()}` };
  }
  if (monthlyPrice && monthlyPrice > 0) {
    return { label: 'Annual value', value: `~$${(monthlyPrice * 12).toLocaleString()}/yr` };
  }
  return { label: 'At risk', value: 'N/A' };
}

// ── TypeScript-rendered Section 3 ────────────────────────────────────────────
// Never delegated to the model. Structured data → deterministic HTML.

function renderFinancialOption(opt: FinancialOption, stepNumber: number): string {
  const mgr = opt.requiresManager ? ' <b>⚠️ MGR</b>' : '';
  // Trim script to first sentence — max ~15 words in practice
  const script = opt.script.split(/(?<=[.?!])\s+/)[0] ?? opt.script;
  return `<li>${stepNumber}. ${opt.label}${mgr} — &ldquo;${script}&rdquo;</li>`;
}

function buildSection3Block(
  brief: RetentionBrief,
  gapAudit: GapAuditResult | null,
  topGaps: string[]
): string {
  const s3 = brief.section3;
  const sequence = s3.escalationSequence ?? [];

  const sequenceHtml = sequence.length > 0
    ? `<ol>${sequence.map((opt, i) => renderFinancialOption(opt, i + 1)).join('\n')}</ol>`
    : '<i>No escalation options.</i>';

  const gapFooter = topGaps.length > 0
    ? `<b>🔍 Top gaps:</b><ul>${topGaps.map(g => `<li>${g}</li>`).join('')}</ul><hr>`
    : '';

  return `<hr>
<b>Section 3 — Economics &nbsp;⚠️ LAST RESORT — only after S1 + S2 rejected</b><br>
${sequenceHtml}
<hr>
${gapFooter}
<p><i>Generated by TSI Retention Agent &middot; ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</i></p>`;
}

// ── Haiku prompt: narrative sections only (agentBrief, S1, S2) ───────────────
// TARGET: SHORT. An agent glances at this before dialing. Every field should be
// readable in 5 seconds. No paragraph narration — bullets only. Scripts max 2 sentences.

function buildNotePrompt(
  brief: RetentionBrief,
  gapAudit: GapAuditResult | null,
  clientName: string,
  agentNotes: string,
  productsLine: string,
  atRisk: { label: string; value: string },
  enrichedAgentNotes: string = '',
  saveabilityScore: string = 'Recoverable',
): string {
  const tsiServiceGapNote = ''; // gap data stays in MongoDB — removed from note content

  const isUnderContract = brief.agentBrief?.contractNote?.includes('UNDER CONTRACT') ?? false;

  return `You are transcribing a retention brief into a Freshdesk internal note. Write clean HTML using ONLY: <b>, <br>, <ul>, <li>, <hr> tags.

PRIMARY RULE — DO NOT PARAPHRASE OR REWRITE. Copy the actual content from the brief data verbatim. Preserve all numbers, names, dollar amounts, and specific language exactly as written. If the brief says "385 people called from Google," the note says "385 people called from Google" — not "strong Google performance" or "meaningful call activity." Rewriting destroys the specificity that makes this brief valuable.

TWO REGISTERS — CRITICAL:
The "Before you dial" section is INTERNAL — the agent reads it privately. You MAY include honest TSI context here. Do NOT reference absent platform data or data limitations.
The Section 1 and Section 2 scripts are SPOKEN TO THE CLIENT. NEVER include TSI failure language, apologies, or "we haven't done X." Scripts must be forward-looking, confident, and specific.

PRODUCT NAMING — CRITICAL: Never use vendor names. "BMP" not vcita · "Directories" not Yext · "Website" not Duda · GBP is fine.

TRANSCRIPTION RULES:
- Pull each field's content from the brief JSON. Copy verbatim — do not rewrite, summarize, or improve it.
- Scripts (agentScript fields): copy verbatim. Do not condense to 2 sentences unless the field is already short.
- Commitments: copy title and description verbatim from the commitments array.
- Loss items: copy asset, disappearsBy, and impact verbatim from lossTimeline. Preserve numbers exactly.
- agentBrief fields (clientSnapshot, cancelReasonRead, leadWith, verticalNote): copy verbatim from agentBrief.
- Notable bullet: only add if the brief data contains a genuinely strong positive signal not already covered above. Skip if nothing stands out.
- Bullets only — no paragraph prose anywhere in the output.
${isUnderContract ? '\nCONTRACT CLIENT: Put the contract callout FIRST in the Before You Call section. The tone is patient — more time, not panic.' : ''}

Client: ${clientName}
Tenure: ${brief.tenureMonths} months | ${atRisk.label}: ${atRisk.value}
Products: ${productsLine || 'Unknown'}
Saveability: ${saveabilityScore}
Agent notes at ticket creation: ${agentNotes || 'None'}
${enrichedAgentNotes ? `Full ticket context (conversations + notes — use for Before You Dial opening posture):
${enrichedAgentNotes}` : ''}
// Gap data not passed to note writer — stored in MongoDB separately

Brief data (pull the actual content from here — do not paraphrase):
${JSON.stringify({
  agentBrief: brief.agentBrief,
  section1: { headline: brief.section1.headline, commitments: brief.section1.commitments, agentScript: brief.section1.agentScript },
  section2: { headline: brief.section2.headline, lossTimeline: brief.section2.lossTimeline, yearsOfWorkStatement: brief.section2.yearsOfWorkStatement, agentScript: brief.section2.agentScript },
  pipelineAtRisk: brief.pipelineAtRisk,
  tenureMonths: brief.tenureMonths,
}, null, 2)}

Write this EXACT HTML structure — fill every bracketed item with real content from the brief data above:

<b>🔴 ${clientName.toUpperCase()} — RETENTION BRIEF</b><br>
<b>Tenure:</b> ${brief.tenureMonths}mo &nbsp;|&nbsp; <b>${atRisk.label}:</b> ${atRisk.value}<br>
<b>Products:</b> ${productsLine}<br>
<b>Saveability:</b> <b>${saveabilityScore === 'Likely Lost' ? '🔴 Likely Lost' : saveabilityScore === 'High Save Probability' ? '🟢 High Save Probability' : '🟡 Recoverable'}</b><br>
<i style="font-size:11px;color:#666">This brief is a starting point — adjust based on what you hear in the first 60 seconds.</i><br>
<hr>
${brief.agentBrief?.contractNote ? `<b>${brief.agentBrief.contractNote}</b><br>` : ''}<b>📋 Before you dial:</b>
<ul>
<li><b>Snapshot:</b> [1-bullet clientSnapshot — max 15 words]</li>
<li><b>Cancel read:</b> [1-bullet cancelReasonRead — max 12 words]</li>
<li><b>Opening posture:</b> [openingPosture — human acknowledgment, max 15 words, NOT data]</li>
<li><b>Facts to deploy when relevant:</b> [factsToDeployLater — data point to introduce as new info, max 15 words]</li>
<li><b>Context:</b> [1-bullet verticalNote — max 15 words]</li>
// TSI service gap bullet removed — gap data stays in MongoDB
[If anything is genuinely notable from the data — strong GBP metrics, high review count, significant lead volume, or a major gap — add 1-2 <li><b>Notable:</b> [finding — max 20 words]</li> bullets here. Skip entirely if nothing stands out.]
</ul><hr>
<b>Section 1 — Opportunity</b><br>
<b>Open with:</b> [brief.section1.headline]<br>
<b>Commitments:</b>
<ul>
[one <li> per commitment: <b>title</b> — expected impact, max 10 words each]
</ul>
<b>Script (2 sentences ONLY):</b> [Opening sentence from brief.section1.agentScript — the hook with 1 number. Then a direct yes/no question. CONDENSE — do not copy the full script.]<br><hr>
<b>Section 2 — Fear / Loss</b><br>
<b>Open with:</b> [brief.section2.headline]<br>
<b>What goes away:</b>
<ul>
[one <li> per loss item — FORMAT STRICTLY: <b>asset name + key number</b> · timing. NO full sentences. Example: <b>$100k pipeline + 21 invoices</b> · gone Day 1]
</ul>
<b>[brief.section2.yearsOfWorkStatement — CONDENSE to 1 short sentence, max 15 words]</b><br>
<b>Script (2 sentences ONLY):</b> [Sentence 1 from brief.section2.agentScript — the biggest loss in 1 sentence. Then: "Is it okay if all of that happens?"]<br>

RULES:
- BULLETS ONLY — no paragraph prose anywhere in the output
- Fill ALL bracketed placeholders with actual content from the brief data
- Return ONLY the HTML — no markdown, no preamble, no explanation
- Do NOT close with <hr> — the system appends Section 3 after your output
- If a field would make you write a paragraph, cut it to a bullet`;
}

// ── Main export ───────────────────────────────────────────────────────────────

export async function writeRetentionNote(
  ticketId: number,
  brief: RetentionBrief,
  gapAudit: GapAuditResult | null,
  clientName: string,
  agentNotes: string,
  serviceKeys: string[] = [],
  monthlyPrice: number | null = null,
  enrichedAgentNotes: string = '',  // includes ticket conversation history for "Before you dial"
): Promise<{ noteId: number; noteUrl: string }> {

  // Pre-compute TypeScript-rendered header values
  const productsLine = renderProducts(serviceKeys);
  const atRisk = computeAtRiskHeader(brief.pipelineAtRisk, monthlyPrice);

  // Gap data stays in MongoDB for learning — not surfaced in the agent note
  const topGaps: string[] = [];

  // Step 1: Haiku generates the narrative sections (agentBrief, S1, S2)
  const apiKey = getAnthropicApiKey();

  const saveabilityScore = (brief as unknown as { saveabilityScore?: string }).saveabilityScore
    ?? (gapAudit as unknown as { saveabilityScore?: string })?.saveabilityScore
    ?? 'Recoverable';

  const aiResponse = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    signal: AbortSignal.timeout(60_000), // 1-min cap — Haiku is fast; hang = something wrong
    headers: {
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 2000,  // S1+S2+brief only — Section 3 is TypeScript-rendered
      messages: [{
        role: 'user',
        content: buildNotePrompt(brief, gapAudit, clientName, agentNotes, productsLine, atRisk, enrichedAgentNotes, saveabilityScore),
      }],
    }),
  });

  if (!aiResponse.ok) {
    const errBody = await aiResponse.text().catch(() => '');
    throw new Error(`Note writer (Haiku) error: ${aiResponse.status} ${aiResponse.statusText}${errBody ? ` — ${errBody.slice(0, 200)}` : ''}`);
  }

  const aiResult = await aiResponse.json() as { content: Array<{ type: string; text: string }> };
  const rawNarrativeHtml = aiResult.content?.[0]?.text;
  if (!rawNarrativeHtml) throw new Error('Empty response from note writer');

  // Strip HTML code fences — Haiku intermittently wraps output in ```html ... ``` despite
  // being told not to. Leading \s* handles newlines Haiku sometimes emits before the fence.
  const narrativeHtml = rawNarrativeHtml
    .replace(/^\s*```(?:html)?\s*/i, '')
    .replace(/\s*```\s*$/i, '')
    .trim();

  // Step 2: TypeScript appends Section 3 (deterministic, no model interpretation)
  const section3Html = buildSection3Block(brief, gapAudit, topGaps);
  const fullNoteHtml = narrativeHtml + '\n' + section3Html;

  // Step 3: Post as internal note to Freshdesk ticket
  const { apiKey: fdApiKey, domain } = await getFreshdeskCredentials();
  const auth = Buffer.from(`${fdApiKey}:X`).toString('base64');

  const fdResponse = await fetch(`https://${domain}/api/v2/tickets/${ticketId}/notes`, {
    method: 'POST',
    headers: {
      'Authorization': `Basic ${auth}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      body: fullNoteHtml,
      private: true,  // internal note — not visible to client
    }),
    signal: AbortSignal.timeout(15000),
  });

  if (!fdResponse.ok) {
    const errText = await fdResponse.text();
    throw new Error(`Freshdesk note POST failed: ${fdResponse.status} — ${errText.slice(0, 200)}`);
  }

  const fdResult = await fdResponse.json() as { id: number };
  return {
    noteId: fdResult.id,
    noteUrl: `https://${domain}/helpdesk/tickets/${ticketId}`,
  };
}
